services:
  - type: web
    name: colonel-mod-bot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: BOYKISSER_OFFICER_GAYGENERAL
        sync: false
      - key: BOYKISSER_OFFICER_BOYKISSER3
        sync: false
      - key: BOYKISSER_OFFICER_FURRYSTALKINGCORNER
        sync: false
